package org.onetwo.common.db.spi;

/**
 * @author weishao zeng
 * <br/>
 */

public interface NamedQueryInfo {

	String getFullName();

	String getName();

	String getCountName();
	
	FileSqlParserType getParserType();

	boolean isAutoGeneratedCountSql();
	
	default boolean isNativeSql() {
		return true;
	}
	
	QueryConfigData getQueryConfig();
	
	/***
	 * 获取查询的命令空间
	 * @author weishao zeng
	 * @return
	 */
	String getNamespace();
	
	/***
	 * 根据attr参数获取sql片段
	 * @author weishao zeng
	 * @param attr
	 * @return
	 */
	String getFragmentTemplateName(String attr);
	/*public String getCountSql2() {
		if(StringUtils.isBlank(countSql)){
			this.countSql = ExtQueryUtils.buildCountSql(this.getSql(), "");
		}
		return countSql;
	}*/

}